[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[lib]
path = "src/lib.rs"

[dependencies]
axum = "0.6.20"
hyper = "0.14.27"
reqwest = "0.11.18"
tokio = { version = "1.30.0", features = ["macros", "rt-multi-thread"] }
